### PR TITLE
Bugfix for incorrect movement of expressions in init block

### LINKED ISSUE #1132: SingleConstructorRule: incorrect movement of expressions in init block
Here is the code:
```
class Test {
    constructor() {
        str = "ABC"
        println(str)
        str = str.reversed()
        println(str)
    }
    var str: String
}
```
After diktat fix we will get this code:
```
class Test {
    init {
        println(str)
        println(str)
        str = "ABC"
        str = str.reversed()
    }
    var str: String
}
```
which is obviously wrong.

### PR DESCRIPTION
**Pull request by sanyavertolet**
## SingleConstructorRule

This pull request closes #1132 

## Actions checklist
* [ ] Fixed bug
* [ ] Added test

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt [hunk 1]
```diff
@@ -122,7 +125,15 @@ class SingleConstructorRule(configRules: List<RulesConfig>) : DiktatRule(
             }
             .distinct()
 
-        classNode.convertSecondaryConstructorToPrimary(secondaryCtor, declarationsAssignedInCtor, nonTrivialAssignments, otherStatements, comments)
+        // future init body
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt:128]: Please describe more verbosely which expressions you are collecting here

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt [hunk 2]
```diff
@@ -122,7 +125,15 @@ class SingleConstructorRule(configRules: List<RulesConfig>) : DiktatRule(
...
+        val expressions = (secondaryCtor.psi as KtSecondaryConstructor)
+            .bodyBlockExpression
+            ?.statements
+            ?.map { it.text }
+            ?.filter { expr -> expr in otherStatements.map { it.text } || expr in nonTrivialAssignments.keys.map { it.text } }
+            ?: emptyList()
+
+        classNode.convertSecondaryConstructorToPrimary(secondaryCtor, declarationsAssignedInCtor, nonTrivialAssignments, otherStatements, comments, expressions)
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt:136]: I think it would be more clear to pass all statements into the function and then split them into groups there (if that's what you're doing and if it doesn't cause a lot of changes in existing code)

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt (hunk 1 above)
Comment (sanyavertolet) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt:128]: Well there are those and only those expressions that later will be in init block

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt (hunk 2 above)
Comment (sanyavertolet) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt:136]: Either I split those two functions into few small ones or I remain it as is. What is the best solution for now?

Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/SingleConstructorRule.kt:136]: Ok, let's keep it

**Review by petertrr — APPROVED** [review]
