### PR TITLE
Fix: Don't remove newline when moving comments into class KDoc

### LINKED ISSUE #1115: Fix: Incorrect break of newlines in primary constructor
```
// Reflekt/SmartReflekt content types
enum class ReflektEntity(
    val entityType: String,     // objects/classes/functions
        val smartClassName: String,  // SmartReflekt nested class - [Object/Class/Function]CompileTimeExpression
)
```
=>
```
/**
 * @property entityType
 * @property smartClassName objects/classes/functions
 */
// Reflekt/SmartReflekt content types
enum class ReflektEntity(
    val entityType: String, val smartClassName: String,  // SmartReflekt nested class - [Object/Class/Function]CompileTimeExpression
)
```

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Refactoring in `KdocComments`
* Fix in logic: don't remove `WHITE_SPACE` nodes when moving comment node
* Added tests
* Fixed bug with incorrect `isFixMode` flag in `KdocComments`

## Which rule and warnings did you add?
This pull request closes #1115

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt [hunk 1]
```diff
@@ -209,17 +214,21 @@ class KdocComments(configRules: List<RulesConfig>) : DiktatRule(
         // if property is documented with KDoc, which has a property tag inside, then it can contain some additional more complicated
         // structure, that will be hard to move automatically
         val isFixable = propertyInLocalKdoc == null
-        KDOC_NO_CONSTRUCTOR_PROPERTY.warnAndFix(configRules, emitWarn, isFixable, prevComment.text, prevComment.startOffset, node, isFixable) {
```
Comment (petertrr) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:212]: There was a bug all this time, we were luckily only receiving `false` here, it seems. Or never running diktat in check mode

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt [hunk 2]
```diff
@@ -170,26 +175,26 @@ class KdocComments(configRules: List<RulesConfig>) : DiktatRule(
...
-                "/**\n * @property ${node.findChildByType(IDENTIFIER)!!.text}${prevComment.text.removePrefix("/*").removeSuffix("*/")} */"
+                "/**\n * @property ${valueParameterNode.findChildByType(IDENTIFIER)!!.text}${prevComment.text.removePrefix("/*").removeSuffix("*/")} */"
             }
             val newKdoc = KotlinParser().createNode(newKdocText).findChildByType(KDOC)!!
             classNode.addChild(PsiWhiteSpaceImpl("\n"), classNode.firstChildNode)
             classNode.addChild(newKdoc, classNode.firstChildNode)
-            if (prevComment.elementType == EOL_COMMENT) {
-                node.treeParent.removeRange(prevComment, node)
-            } else {
+            if (prevComment.elementType == KDOC) {
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:191]: Can we extract this logic into the separate method?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt [hunk 3]
```diff
@@ -209,17 +214,21 @@ class KdocComments(configRules: List<RulesConfig>) : DiktatRule(
...
+        KDOC_NO_CONSTRUCTOR_PROPERTY.warnAndFix(configRules, emitWarn, isFixMode, prevComment.text, prevComment.startOffset, node, isFixable) {
             propertyInClassKdoc?.let {
                 // local docs should be appended to docs in class
                 appendKdocTagContent(propertyInClassKdoc, "\n$kdocText")
             }
                 ?: insertTextInKdoc(kdocBeforeClass, " * @property ${node.findChildByType(IDENTIFIER)!!.text} ${kdocText.removePrefix("*")}\n")
 
-            if (prevComment.treeNext.elementType == WHITE_SPACE) {
-                node.removeChild(prevComment.treeNext)
+            if (prevComment.elementType == KDOC) {
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:224]: These logic seems to be very similar to  part from previous review comment

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt [hunk 4]
```diff
@@ -330,3 +339,24 @@ class KdocComments(configRules: List<RulesConfig>) : DiktatRule(
         private val statementsToDocument = TokenSet.create(CLASS, FUN, PROPERTY)
     }
 }
+
+/**
+ * If [child] node is surrounded by nodes with type `WHITE_SPACE`, remove [child] and merge surrounding nodes,
+ * preserving only a single newline if present (i.e. leaving no empty lines after merging). In any case, [child] is removed
+ * from the tree.
+ */
+private fun ASTNode.removeChildMergingSurroundingWhitespace(child: ASTNode) {
```
Comment (kgevorkyan) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:348]: ?
```suggestion
private fun ASTNode.removeChildMergingSurroundingWhitespaces(child: ASTNode) {
```

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+ * @property param2  first comment
+*/
+class Example(
+    val param1: String,
+    val param2: String, // second comment
+)
+
+/**
+ * @property param1
+  * @property param2 first comment
```
Comment (kgevorkyan) [inline diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt:14]: Extra whitespace?

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt [hunk 6]
```diff
@@ -0,0 +1,19 @@
+package test.paragraph2.kdoc
+
+/**
+ * @property param1
+ * @property param2  first comment
```
Comment (kgevorkyan) [inline diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt:5]: But here is all okay

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt [hunk 7]
```diff
@@ -0,0 +1,19 @@
...
+*/
+class Example(
+    val param1: String,
+    val param2: String, // second comment
```
Comment (kgevorkyan) [inline diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt:9]: Initially, I thought, that the main problem is that we mixed up the comments, since they are inline

May be  we can at least open an separate issue for this?

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt (hunk 2 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:191]: Extracted

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt (hunk 4 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt]: +

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt (hunk 5 above)
Comment (akuleshov7) [reply diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt:14]: but diktat passed... how

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt (hunk 1 above)
Comment (akuleshov7) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:212]: oh

**Review by akuleshov7 — APPROVED** [review]

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt (hunk 1 above)
Comment (petertrr) [reply diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter2/kdoc/KdocComments.kt:212]: Yes, I discovered this bug when my new tests have started failing. So now it's covered by those.

File: diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt (hunk 7 above)
Comment (petertrr) [reply diktat-rules/src/test/resources/test/paragraph2/kdoc/ConstructorCommentNewlineExpected.kt:9]: Yes, created #1125. For now we are focusing on bugfixes only, and major logic enhancements should be postponed till after 1.0.0.
