### PR TITLE
Fix: Don't remove `abstract` for subclasses

### LINKED ISSUE #1114: [CLASS_SHOULD_NOT_BE_ABSTRACT] should be applied to classes that does not have parental class
```
abstract class ClassesOrObjectsGenerator(protected val uses: ClassOrObjectUses) : HelperClassGenerator() {
```

if `HelperClassGenerator` is abstract, `ClassesOrObjectsGenerator` can be also abstract

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Fix in logic
* Tests

## Which rule and warnings did you add?

This pull request closes #1114

### CODE REVIEW

File: diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/AbstractClassesRule.kt [hunk 1]
```diff
@@ -29,14 +32,20 @@ class AbstractClassesRule(configRules: List<RulesConfig>) : DiktatRule(
...
             }
         }
     }
 
-    private fun hasAbstractModifier(node: ASTNode): Boolean =
-            node.getFirstChildWithType(MODIFIER_LIST)?.hasChildOfType(ABSTRACT_KEYWORD) ?: false
+    private fun ASTNode.hasAbstractModifier(): Boolean =
+            getFirstChildWithType(MODIFIER_LIST)?.hasChildOfType(ABSTRACT_KEYWORD) ?: false
+
+    private fun ASTNode.isNotSubclass(): Boolean = findChildByType(SUPER_TYPE_LIST)?.children()?.filter {
```
Comment (akuleshov7) [inline diktat-rules/src/main/kotlin/org/cqfn/diktat/ruleset/rules/chapter6/classes/AbstractClassesRule.kt:46]: I have incorrectly called it subclass. But it is called child class

**Review by akuleshov7 — APPROVED** [review]
